### ISSUE TITLE
Report success 8/9 series HP Laptop

### ISSUE THREAD

**Issue by chris1111** [chris1111/HP-Probook-EliteBook-Package-Creator#8]
Please report success 8/9 series HP Laptop here with complet specs
Thanks

**Comment by Al-Baby6666** [comment]
Using the new issue of PBI (beta)on a HP Elitebook 820 G2-with High Res Screen and i& CPU-I was able to easily install El-Capitan-having changed the Wi-Fi to a broadcom one.
The only outstanding issue is the Battery charging is not recognised- shows the power supply as being plugged in but "about Mac "shows no battery charge. Otherwise everything works even sleep.
So I am extremely grateful to you for that-and cannot thank you enough.
I have also installed High Sierrra using PBI beta -but the Keypad is blank -so I went back to El-Capitan .
Your PBI will allow many more people -to get their HP Laptops Hackingtoshed without needing a deep knowledge of computer language. So I thank you again for that

**Comment by Al-Baby6666** [comment]
I forgot the other item not woking on my Eliteboot 820 G2 with the new PBI (Beta) is the Brightness control .

**Comment by chris1111** [comment]
> I forgot the other item not woking on my Eliteboot 820 G2 with the new PBI (Beta) is the Brightness control .

Thanks  @Al-Baby6666 
Your not try macOS Mojave ?

**Comment by chris1111** [comment]
> Using the new issue of PBI (beta)on a HP Elitebook 820 G2-with High Res Screen and i& CPU-I was able to easily install El-Capitan-having changed the Wi-Fi to a broadcom one.
> The only outstanding issue is the Battery charging is not recognised- shows the power supply as being plugged in but "about Mac "shows no battery charge. Otherwise everything works even sleep.
> So I am extremely grateful to you for that-and cannot thank you enough.
> I have also installed High Sierrra using PBI beta -but the Keypad is blank -so I went back to El-Capitan .
> Your PBI will allow many more people -to get their HP Laptops Hackingtoshed without needing a deep knowledge of computer language. So I thank you again for that

Thanks  @Al-Baby6666  to report

**Comment by Al-Baby6666** [comment]
Hi Chris
I now have a fully working High Sierra HP Elitebook 820 G2 with Full HD graphics-everything works -including backlight control. I did this by a combination of your PBI and the other PBI from Tony Macs.which has just been updated (like your PBI)  to cover the G2  I kept switching from one PBI to the other -changing options each time until I got the perfect result. 
I am not sure but I think that your PBI gets the correct Kexts required but does not fully produce the correct DSDT or SSDT  files .
I tried to attach the EFI below but it will not accept file because its to big?
The only item that does not work is the SD card reader.

I also did the same PBI switching technique for my HP Elitebook 820 G1 with low res graphics And that Laptop has Yosemite fully working. So am very happy.
I am not very good at computer programing -rather I am a computer user-so your method was the only way for me -for that I thank you. I would also like to support you for your time in developing this method with a contribution-but have found this to be difficult because your web site does not recognise my password-can you help? Maybe I can send a direct paypal payment to your email .
Thanks again 
Regrds -Al-Baby

**Comment by Al-Baby6666** [comment]
![system report](https://user-images.githubusercontent.com/45580940/50374046-dd4a7100-05df-11e9-8f44-ab66f24da1c7.jpeg)
